name: Node CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      working-directory: .
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: set environment variables
        uses: allenevans/set-env@v1.0.0
        with:
          GATSBY_SYLIUS_URL: ${{ secrets.SYLIUS_URL }}
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build --if-present
          start: npm start
          wait-on: http://localhost:8000
