name: Node CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      working-directory: .
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: set environment variables
        uses: allenevans/set-env@v1.0.0
        with:
          GATSBY_SYLIUS_URL: ${{ secrets.SYLIUS_URL }}
      - name: install
        working-directory: ${{env.working-directory}}
        run: npm ci
        env:
          CI: true
      - name: run cypresse tests
        run: npm run test:e2e:ci
        env:
          CI: true
      - name: build
        if: github.ref == 'refs/heads/master'
        run: npm run build
        env:
          CI: true
      - name: deploy
        if: github.ref == 'refs/heads/master'
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-e -c -r --delete"
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          FOLDER: "./public/"
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
          SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
